version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'zukk'
      MYSQL_PASSWORD: 'zukk'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #       - 5040:5040
  #   volumes:
  #       - rabbitmq-data:/var/lib/rabbitmq
  #       - rabbitmq-log:/var/log/rabbitmq
  redis:
    image: "redis:alpine"
    container_name: 'redis'
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  my-db:
  rabbitmq-data:
  rabbitmq-log:
  redis-data: