version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'zukk'
      MYSQL_PASSWORD: 'zukk'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./config/mysql_custom.cnf:/etc/mysql/conf.d/mysql_custom.cnf
  messages-db-1:
    image: mysql:8.0
    container_name: messages-db-1
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'zukk'
      MYSQL_PASSWORD: 'zukk'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - messages-db-1:/var/lib/mysql
  messages-db-2:
    image: mysql:8.0
    container_name: messages-db-2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'zukk'
      MYSQL_PASSWORD: 'zukk'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - messages-db-2:/var/lib/mysql
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    volumes:
      - proxysql-data:/var/lib/proxysql
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 5040:5040
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq
        - rabbitmq-log:/var/log/rabbitmq
  redis:
    image: "redis:alpine"
    container_name: 'redis'
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  tarantool:
    image: "tarantool/tarantool:1.10.9"
    container_name: 'tarantool'
    ports:
      - "3301:3301"
    volumes:
      - tarantool-data:/var/lib/tarantool
      - ./tarantool:/usr/local/share/tarantool

volumes:
  my-db:
  messages-db-1:
  messages-db-2:
  proxysql-data:
  rabbitmq-data:
  rabbitmq-log:
  redis-data:
  tarantool-data:
