version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'zukk'
      MYSQL_PASSWORD: 'zukk'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    deploy:
        resources:
            limits:
              cpus: 6
              memory: 6G
            reservations:
              cpus: 1
              memory: 512M
volumes:
  my-db: